title: Cayman theme
description: App that allows restaurants, hypermarkets...to sell their food leftovers of the day at a cheaper price to customer in order to avoid food wasting.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
